language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "f8QHTRPhnzVEV1hiHM9W/vE9HVDeX8DDqjyt8DfUF70+qnKQzyPqFR4+5nK5QSLV2pc4yO1bZxoMTWAz6+w+KQRdNL8Qk23ni1dhulWhdFpcMXN1y1xeIw8n5oujwufeZqhssGIuap/hHVPfyFyYsc2BpWFf9QwIXByHXAdRpf9EtN8aaTFX3MePTq1WSNAWi+grwiozN7bi3cqIwfBjFqFmP5IrTpEmp1BP6F7jIAZ+RXvYuYo3uiWyWQBQ/m7ATCbY7lbLR9DwCtFN0cSCfg29lR5ydCTWhGUhhkCVlHVlce8fqrl2QahPryqnyQ9YpYnpNF1v9zA5QHvOfoRKsa7nzzCPG/8i9Wn3NCmADip+4AgFdU3CR7wrnHsR3D5ZTTRx0lcPtKovu6v2Go9fM9wmNmgFUMyqW9djuwb9yI2VNTTX8pBhvN16YbicvlZ63jlcjkKBSWlTvcIRSVh1tyTheYOTyc1PpyD3y3Nm0lYfjj07siv7CKzVmPFGuHjuDg6LHzgj/yLrK0Z7DOSLPpTkr7/25ohfTl3C0DgTA5D91Yj1SGz9mi7XmquSc5aeTwIbcMwvkK4bXxqm3HAlAOTDHi2rhnSykQnZECRnIh4SkvNzum8fMKw+UTApMW8wLzynPv7QZPicT/NiFWtaPzkNUa4mAjoPUkdaOpSj+2Q="
  - secure: "kgrwOCzLT59c9lA9yMNQTLC49yWb/PvdEMT+9hQu7Kub65wCaLvndMaBXvmoydPf1DAEMdTNBoUCLRwCddxaU5/Nw3Bc3AVUBAF7Vr/G4PPRynbOEnTObkq0NeFjPgZytejRa7v8tbqITbtFr4uacyYBE/lLS0W3tqkSEVbql7N7JkAuNMMWlcrONMEN6X8pekLygPKpNi7vzs0ciC6MJgRSI81zCEA1n165czTCvOgZ7TPCSrz/YeGV9WRQH3+EUGu/La2H2o2PIN4v7h+R9Sd5YmvcnTVR/eF83vkJ5RJW2dDEoQtAV+nwf4Pmer83XfAwx3LoNpRHNcDNC08HRXGgu8CVFuqnPPLO90hMa7YGZhuNNQW4di707dIbdT3LJGaywlAJsrJePKoegkgAiQW6pPXDk1J1ahwUrgwK7R7Cw4MJOvirKRM9Llrp96JqxOc3ktgIiXIS65rFWbzxBmITmK+XQitnteCvCq1H/kt4S+/12ZWIGO/+AUR2AW72nI20YP6C/YdtE0oQxAHZYjDhv/eieyyOoqX7Zm7y4ZbLSfXvsanRJKWqqLv988iUFbfgcqpk+ljzwWbtXOuWnUGpTx4f64AD9pqNWxYP+SaSUGjKZZquhnJfTXH3Us1xQFMblGqjFHbiLnFqnYUt04FhFAsgjnXCgxjmOg5At0Q="
deploy:
  provider: releases
  api_key: 
    secure: "DyOAGRndih4L+seHXxhTieQymSm/3Zlz2lkN5df0yiY5qb+6Iu4rLfwr4mk0QaEaBsIVMWKMa69sx574Imel7/JXYUwxTtvoKUmdRZ8qpXjz/2xrqAPGzCHyXvhhf6X5iLe8+sz6LI7PMHFgw/bBXJrRgO2ngXwEYPAm73D+BibW5b3eRi+CRcH5apghaewMp9UyhhTXqJMongv8MuKsVK++bWMgZCVCdqnxzU1sdilGF3dUW1rN8QEtjgD3ruFu/e3H+AfS6/gIl6zUKALgSsDJ7O9TnUyWWR4RQtG9qfnBLO0m4q3gXbIXL4gFcvMEXccVDRuEZpl4R7685M98im7Oz8l61Nd5X9ZEylGJLG38XPOYsIKaQxWH8uqhUDd5R0PyK5x5hH8DRs5qz3VRloYSsfTZF4CfHZ14mU7jN3lZxw2sjrS7axTG39WGnp4ivNpGNWpW1eJtYNIPD7t3oP3OzKxWLXxQtLuivrR4su9izdhNBBv6LtpVkizx8fFaZdoqRRwAkoEllf/ZTrCKmSx2+zLoNF1jBN1scp3E3XdBIDp2WrYAS+qo/uhKN0GSyOw7ZUxU9TDHpq+5OTlWraxZrS50PhyMZc+HJM3wmtkFGqu+O2DHbzCbEnzxNNv3ARhdE6SdQkNjq6B9T0LO2oQrugBsY4zzS8VyxEVXE5g="
  file_glob: true
  file: 
    - "target/EventCallbacks_v*.jar"
  skip_cleanup: true
  on:
    tags: true
